name: Validations

on:
  pull_request:
    paths:
      - 'TP2/**'
      - '.github/workflows/validations.yml'

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  verifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.2"

      - name: Install Ceedling
        run: gem install ceedling

      - name: Install GCov Reporter
        run: pip install gcovr

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Debug clang-format config
        run: cat TP2/.clang-format


      - name: Run Format Validations (Pre-commit in TP2)
        run: |
          cd TP2
          pre-commit install
          pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Run Unit Tests
        run: |
          cd TP2
          ceedling clobber gcov:all

      - name: Test Results Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Ceedling Unit Tests
          path: TP2/build/artifacts/gcov/junit_tests_report.xml
          reporter: jest-junit

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: TP2/build/artifacts/gcov/gcovr/GcovCoverageCobertura.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "75 90"

      - name: Output to Job Summary
        run: cat TP2/code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: TP2/code-coverage-results.md
