name: Validations

on:
  pull_request:
    branches: [main]
    paths:
      - 'TP02/**'   # Se activa solo si se modifican archivos dentro de TP02

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  verifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.2"

      - name: Install Ceedling
        run: gem install ceedling

      - name: Install GCov Reporter
        run: pip install gcovr

      - name: Run Format Validations
        uses: pre-commit/action@v3.0.0

      - name: Run Unit Tests
        working-directory: TP02   # Se establece el directorio de trabajo en TP02
        run: ceedling clobber gcov:all

      - name: Test Results Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Ceedling Unit Tests
          path: TP02/build/artifacts/gcov/junit_tests_report.xml   # Ruta ajustada a TP02
          reporter: jest-junit

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: TP02/build/artifacts/gcov/gcovr/GcovCoverageCobertura.xml   # Ruta ajustada a TP02
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "75 90"

      - name: Output to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
